# Fetching the minified node image on apline linux
FROM node:10

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /pathotech-api

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install

# Starting our application
CMD [ "node", "app.js" ]

# Exposing server port
EXPOSE 3000